"""SQLAlchemy ORM models for SAHAYI."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base ORM class for all SAHAYI tables.

    Args:
        None: Declarative SQLAlchemy base.
    Returns:
        Base subclass for mapped models.
    Agent:
        Database
    """


class Patient(Base):
    """Patient master record.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        Patient ORM class.
    Agent:
        Database
    """

    __tablename__ = "patients"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    language: Mapped[str] = mapped_column(String(20), nullable=False, default="ml-IN")
    phone_number: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    registration_number: Mapped[str | None] = mapped_column(String(64), unique=True, index=True, nullable=True)
    conditions: Mapped[list[str]] = mapped_column(JSON, default=list)
    medicines: Mapped[list[dict]] = mapped_column(JSON, default=list)
    emergency_contact: Mapped[dict] = mapped_column(JSON, default=dict)
    doctor_contact: Mapped[dict] = mapped_column(JSON, default=dict)
    relatives: Mapped[list[dict]] = mapped_column(JSON, default=list)
    doctor_uid: Mapped[str] = mapped_column(String(128), index=True)
    doctor_email: Mapped[str] = mapped_column(String(255), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    call_sessions: Mapped[list["CallSession"]] = relationship(back_populates="patient", cascade="all, delete-orphan")
    signals: Mapped[list["SignalRecord"]] = relationship(back_populates="patient", cascade="all, delete-orphan")
    summaries: Mapped[list["DoctorSummary"]] = relationship(back_populates="patient", cascade="all, delete-orphan")
    memory_notes: Mapped[list["MemoryNote"]] = relationship(back_populates="patient", cascade="all, delete-orphan")


class CallSession(Base):
    """Voice or message session record.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        CallSession ORM class.
    Agent:
        Database
    """

    __tablename__ = "call_sessions"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    session_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    started_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    risk_score: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(20), default="active")
    patient: Mapped["Patient"] = relationship(back_populates="call_sessions")


class SignalRecord(Base):
    """Extracted signal record for one patient turn.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        SignalRecord ORM class.
    Agent:
        Database
    """

    __tablename__ = "signal_records"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    session_id: Mapped[str] = mapped_column(String(64), index=True)
    fatigue: Mapped[bool] = mapped_column(Boolean, default=False)
    appetite: Mapped[str] = mapped_column(String(64), default="unchanged")
    chest_pain: Mapped[bool] = mapped_column(Boolean, default=False)
    duration_days: Mapped[int] = mapped_column(Integer, default=0)
    severity: Mapped[int] = mapped_column(Integer, default=1)
    red_flag: Mapped[bool] = mapped_column(Boolean, default=False)
    symptom_description: Mapped[str] = mapped_column(Text, default="")
    source_text: Mapped[str] = mapped_column(Text, default="")
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    patient: Mapped["Patient"] = relationship(back_populates="signals")


class DoctorSummary(Base):
    """Doctor-facing summary generated by the agent stack.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        DoctorSummary ORM class.
    Agent:
        Database
    """

    __tablename__ = "doctor_summaries"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    summary_text: Mapped[str] = mapped_column(Text, default="")
    risk_score: Mapped[float] = mapped_column(Float, default=0.0)
    rag_context: Mapped[list[dict]] = mapped_column(JSON, default=list)
    hypothesis: Mapped[dict] = mapped_column(JSON, default=dict)
    citations: Mapped[list[dict]] = mapped_column(JSON, default=list)
    knowledge_graph: Mapped[dict] = mapped_column(JSON, default=dict)
    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    patient: Mapped["Patient"] = relationship(back_populates="summaries")


class PopulationPattern(Base):
    """Population intelligence record.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        PopulationPattern ORM class.
    Agent:
        Database
    """

    __tablename__ = "population_patterns"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    pattern_json: Mapped[dict] = mapped_column(JSON, default=dict)
    frequency: Mapped[int] = mapped_column(Integer, default=0)
    research_gap: Mapped[bool] = mapped_column(Boolean, default=False)
    week_delta: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class OrchestrationLog(Base):
    """Routing decision audit log.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        OrchestrationLog ORM class.
    Agent:
        Database
    """

    __tablename__ = "orchestration_logs"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String(64), index=True)
    patient_id: Mapped[int] = mapped_column(Integer, index=True)
    trigger: Mapped[str] = mapped_column(String(80))
    decision: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class MemoryNote(Base):
    """Persistent memory note for companion personality and patient context.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        MemoryNote ORM class.
    Agent:
        Database
    """

    __tablename__ = "memory_notes"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    category: Mapped[str] = mapped_column(String(32), default="context")
    content: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    patient: Mapped["Patient"] = relationship(back_populates="memory_notes")


class MistakeNote(Base):
    """Logged AI mistake so the system can learn from its own errors.

    Stores what the model did, why it was wrong, the correction, and the
    lesson to apply next time. Optionally tied to a patient for context.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        MistakeNote ORM class.
    Agent:
        Database
    """

    __tablename__ = "mistake_notes"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int | None] = mapped_column(ForeignKey("patients.id"), index=True, nullable=True)
    agent: Mapped[str] = mapped_column(String(48), default="orchestrator")
    mistake_type: Mapped[str] = mapped_column(String(48), default="general")
    context: Mapped[str] = mapped_column(Text, default="")
    error: Mapped[str] = mapped_column(Text, default="")
    correction: Mapped[str] = mapped_column(Text, default="")
    lesson: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class RelativeUpdate(Base):
    """Clinical summary of a relative's submission, surfaced to the doctor.

    Relatives may send prescription images, voice notes, or text over WhatsApp.
    To honour the dashboard privacy rule we store only a derived CLINICAL
    summary (never the raw transcript or personal message). Optionally tied to
    a patient; used by the doctor dashboard "Relative Updates" panel.

    Args:
        None: ORM model fields are mapped columns.
    Returns:
        RelativeUpdate ORM class.
    Agent:
        Database
    """

    __tablename__ = "relative_updates"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    relative_name: Mapped[str] = mapped_column(String(120), default="Relative")
    update_type: Mapped[str] = mapped_column(String(32), default="voice_note")
    clinical_summary: Mapped[str] = mapped_column(Text, default="")
    source_detail: Mapped[str] = mapped_column(String(255), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
